name: setup
description: Standard ODW software environment setup.
version: 0.1.1
author: Jim Philbin <jfphilbin@gmail.com>
homepage: https://github.com/OpenDICOMweb/setup

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
